INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mclaren', 'McLaren', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('bmw_sauber', 'BMW Sauber', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('williams', 'Williams', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('renault', 'Renault', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('toro_rosso', 'Toro Rosso', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ferrari', 'Ferrari', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('toyota', 'Toyota', 'Japanese');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('super_aguri', 'Super Aguri', 'Japanese');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('red_bull', 'Red Bull', 'Austrian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('force_india', 'Force India', 'Indian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('honda', 'Honda', 'Japanese');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('spyker', 'Spyker', 'Dutch');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mf1', 'MF1', 'Russian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('spyker_mf1', 'Spyker MF1', 'Dutch');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('sauber', 'Sauber', 'Swiss');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('bar', 'BAR', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('jordan', 'Jordan', 'Irish');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('minardi', 'Minardi', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('jaguar', 'Jaguar', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('prost', 'Prost', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('arrows', 'Arrows', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('benetton', 'Benetton', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brawn', 'Brawn', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('stewart', 'Stewart', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('tyrrell', 'Tyrrell', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lola', 'Lola', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ligier', 'Ligier', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('forti', 'Forti', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('footwork', 'Footwork', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('pacific', 'Pacific', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('simtek', 'Simtek', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('team_lotus', 'Team Lotus', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('larrousse', 'Larrousse', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brabham', 'Brabham', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('dallara', 'Dallara', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('fondmetal', 'Fondmetal', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('march', 'March', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('moda', 'Andrea Moda', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ags', 'AGS', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lambo', 'Lambo', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('leyton', 'Leyton House', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('coloni', 'Coloni', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('eurobrun', 'Euro Brun', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('osella', 'Osella', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('onyx', 'Onyx', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('life', 'Life', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('rial', 'Rial', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('zakspeed', 'Zakspeed', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ram', 'RAM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('alfa', 'Alfa Romeo', 'Swiss');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('spirit', 'Spirit', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('toleman', 'Toleman', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ats', 'ATS', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('theodore', 'Theodore', 'Hong Kong');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('fittipaldi', 'Fittipaldi', 'Brazilian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ensign', 'Ensign', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('shadow', 'Shadow', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('wolf', 'Wolf', 'Canadian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('merzario', 'Merzario', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('kauhsen', 'Kauhsen', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('rebaque', 'Rebaque', 'Mexican');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('surtees', 'Surtees', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('hesketh', 'Hesketh', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('martini', 'Martini', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brm', 'BRM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('penske', 'Penske', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lec', 'LEC', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mcguire', 'McGuire', 'Australian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('boro', 'Boro', 'Dutch');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('apollon', 'Apollon', 'Swiss');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('kojima', 'Kojima', 'Japanese');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('parnelli', 'Parnelli', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('maki', 'Maki', 'Japanese');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('hill', 'Embassy Hill', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lyncar', 'Lyncar', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('trojan', 'Trojan', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('amon', 'Amon', 'New Zealander');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('token', 'Token', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('iso_marlboro', 'Iso Marlboro', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('tecno', 'Tecno', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('matra', 'Matra', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('politoys', 'Politoys', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('connew', 'Connew', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('bellasi', 'Bellasi', 'Swiss');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('tomaso', 'De Tomaso', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper', 'Cooper', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('eagle', 'Eagle', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lds', 'LDS', 'South African');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('protos', 'Protos', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('shannon', 'Shannon', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('scirocco', 'Scirocco', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('re', 'RE', 'Rhodesian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brp', 'BRP', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('porsche', 'Porsche', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('derrington', 'Derrington', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('gilby', 'Gilby', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('stebro', 'Stebro', 'Canadian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('emeryson', 'Emeryson', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('enb', 'ENB', 'Belgian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('jbw', 'JBW', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ferguson', 'Ferguson', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mbm', 'MBM', 'Swiss');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('behra-porsche', 'Behra-Porsche', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('maserati', 'Maserati', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('scarab', 'Scarab', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('watson', 'Watson', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('epperly', 'Epperly', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('phillips', 'Phillips', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lesovsky', 'Lesovsky', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('trevis', 'Trevis', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('meskowski', 'Meskowski', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('kurtis_kraft', 'Kurtis Kraft', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('kuzma', 'Kuzma', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('vhristensen', 'Christensen', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('ewing', 'Ewing', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('aston_martin', 'Aston Martin', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('vanwall', 'Vanwall', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('moore', 'Moore', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('dunn', 'Dunn', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('elder', 'Elder', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('sutton', 'Sutton', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('fry', 'Fry', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('tec-mec', 'Tec-Mec', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('connaught', 'Connaught', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('alta', 'Alta', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('osca', 'OSCA', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('gordini', 'Gordini', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('stevens', 'Stevens', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('bugatti', 'Bugatti', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mercedes', 'Mercedes', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lancia', 'Lancia', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('hwm', 'HWM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('schroeder', 'Schroeder', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('pawl', 'Pawl', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('pankratz', 'Pankratz', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('arzani-volpini', 'Arzani-Volpini', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('nichels', 'Nichels', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('bromme', 'Bromme', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('klenk', 'Klenk', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('simca', 'Simca', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('turner', 'Turner', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('del_roy', 'Del Roy', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('veritas', 'Veritas', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('bmw', 'BMW', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('emw', 'EMW', 'East German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('afm', 'AFM', 'German');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('frazer_nash', 'Frazer Nash', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('sherman', 'Sherman', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('deidt', 'Deidt', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('era', 'ERA', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('butterworth', 'Aston Butterworth', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cisitalia', 'Cisitalia', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lago', 'Talbot-Lago', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('hall', 'Hall', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('marchese', 'Marchese', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('langley', 'Langley', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('rae', 'Rae', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('olson', 'Olson', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('wetteroth', 'Wetteroth', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('adams', 'Adams', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('snowberger', 'Snowberger', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('milano', 'Milano', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('hrt', 'HRT', 'Spanish');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-maserati', 'Cooper-Maserati', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('virgin', 'Virgin', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-osca', 'Cooper-OSCA', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-borgward', 'Cooper-Borgward', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-climax', 'Cooper-Climax', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-castellotti', 'Cooper-Castellotti', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus-climax', 'Lotus-Climax', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus-maserati', 'Lotus-Maserati', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('de_tomaso-osca', 'De Tomaso-Osca', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('de_tomaso-alfa_romeo', 'De Tomaso-Alfa Romeo', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus-brm', 'Lotus-BRM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus-borgward', 'Lotus-Borgward', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-alfa_romeo', 'Cooper-Alfa Romeo', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('de_tomaso-ferrari', 'De Tomaso-Ferrari', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus-ford', 'Lotus-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brabham-brm', 'Brabham-BRM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brabham-ford', 'Brabham-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brabham-climax', 'Brabham-Climax', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lds-climax', 'LDS-Climax', 'South African');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lds-alfa_romeo', 'LDS-Alfa Romeo', 'South African');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-ford', 'Cooper-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mclaren-ford', 'McLaren-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mclaren-seren', 'McLaren-Serenissima', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('eagle-climax', 'Eagle-Climax', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('eagle-weslake', 'Eagle-Weslake', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brabham-repco', 'Brabham-Repco', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-ferrari', 'Cooper-Ferrari', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-ats', 'Cooper-ATS', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mclaren-brm', 'McLaren-BRM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('cooper-brm', 'Cooper-BRM', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('matra-ford', 'Matra-Ford', 'French');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brm-ford', 'BRM-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('mclaren-alfa_romeo', 'McLaren-Alfa Romeo', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('march-alfa_romeo', 'March-Alfa Romeo', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('march-ford', 'March-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus-pw', 'Lotus-Pratt &amp; Whitney', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('shadow-ford', 'Shadow-Ford', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('shadow-matra', 'Shadow-Matra', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('brabham-alfa_romeo', 'Brabham-Alfa Romeo', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus_racing', 'Lotus', 'Malaysian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('marussia', 'Marussia', 'Russian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('caterham', 'Caterham', 'Malaysian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('lotus_f1', 'Lotus F1', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('manor', 'Manor Marussia', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('haas', 'Haas F1 Team', 'American');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('racing_point', 'Racing Point', 'British');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('alphatauri', 'AlphaTauri', 'Italian');
INSERT INTO constructors (constructorRef,name,nationality) VALUES ('alpine', 'Alpine F1 Team', 'French');
